name: Deploy

on:
  workflow_run:
    workflows: [Build and test lab-cicd]
    types: [completed]
    branches: [main]
  # Automatically run this pipeline on every push to the main branch
  # Allow running this pipeline manually from githubs website.
  workflow_dispatch:

jobs:
  build:
    # Run on a ubuntu-22.04 VM image
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    name: Deploy to Digital ocean
    env:
      GITHUB_USER: HeMan
      IMAGE_REGISTRY: ghcr.io/heman
    steps:
      # Checkout our repository
      - uses: actions/checkout@v3
      # Login to our container registry at ghcr.io/YOUR_USER with our credentials
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: "${{ env.IMAGE_REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"

      # Build and push our container image
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        env:
          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
        with:
          token: ${{ secrets.DO_DEPLOY_SECRET }}
